title: Learning
description: Record learning from practice
lang: zh-CN
timezone: Asia/Shanghai
permalink: /:categories/:title/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
